"""Data-store abstraction for AgentHR.

Talks to the store through a unified interface so the exact same code runs against
Amazon DynamoDB (AWS cloud) or an in-process thread-safe store (offline smoke test / demo).
The concrete backend is selected at startup from ``STORE_BACKEND``.
"""
from __future__ import annotations

from datetime import datetime, timezone
from functools import lru_cache
from typing import Any, Optional

from app.config import settings


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


class Store:
    """Interface implemented by MemoryStore and DynamoDBStore."""

    backend: str = "base"

    # -- jobs ----------------------------------------------------------
    def create_job(self, job: dict[str, Any]) -> str: ...
    def get_job(self, job_id: str) -> Optional[dict[str, Any]]: ...
    def list_jobs(self, open_only: bool = False) -> list[dict[str, Any]]: ...
    def update_job(self, job_id: str, updates: dict[str, Any]) -> Optional[dict[str, Any]]: ...

    # -- candidates ----------------------------------------------------
    def create_candidate(self, candidate: dict[str, Any]) -> str: ...
    def get_candidate(self, candidate_id: str) -> Optional[dict[str, Any]]: ...

    # -- applications ---------------------------------------------------
    def create_application(self, app: dict[str, Any]) -> str: ...
    def get_application(self, application_id: str) -> Optional[dict[str, Any]]: ...
    def list_applications(self, job_id: Optional[str] = None) -> list[dict[str, Any]]: ...
    def update_application(self, application_id: str, updates: dict[str, Any]) -> Optional[dict[str, Any]]: ...

    # -- decisions ------------------------------------------------------
    def create_decision(self, decision: dict[str, Any]) -> str: ...
    def get_decision_by_application(self, application_id: str) -> Optional[dict[str, Any]]: ...

    # -- interviews ------------------------------------------------------
    def create_interview(self, interview: dict[str, Any]) -> str: ...
    def list_interviews(self) -> list[dict[str, Any]]: ...
    def get_interview_for_application(self, application_id: str) -> Optional[dict[str, Any]]: ...

    # -- human reviews (Policy Engine Escalations) -----------------------
    def create_human_review(self, review: dict[str, Any]) -> str: ...
    def list_human_reviews(self, status: Optional[str] = None) -> list[dict[str, Any]]: ...
    def update_human_review(self, review_id: str, updates: dict[str, Any]) -> Optional[dict[str, Any]]: ...
    def get_human_review_for_application(self, application_id: str) -> Optional[dict[str, Any]]: ...

    # -- approvals (HITL Approval Gate Checkpoints) -----------------------
    def create_approval(self, approval: dict[str, Any]) -> str: ...
    def get_approval(self, approval_id: str) -> Optional[dict[str, Any]]: ...
    def list_approvals(self, application_id: Optional[str] = None, status: Optional[str] = None) -> list[dict[str, Any]]: ...
    def update_approval(self, approval_id: str, updates: dict[str, Any]) -> Optional[dict[str, Any]]: ...
    def get_approval_for_application(self, application_id: str) -> Optional[dict[str, Any]]: ...

    # -- emails ----------------------------------------------------------
    def create_email(self, email: dict[str, Any]) -> str: ...
    def list_emails(self) -> list[dict[str, Any]]: ...
    def get_email_for_application(self, application_id: str, email_type: Optional[str] = None) -> Optional[dict[str, Any]]: ...

    # -- activity log ----------------------------------------------------
    def create_activity_log(self, entry: dict[str, Any]) -> str: ...
    def append_activity_step(self, run_id: str, step: dict[str, Any]) -> None: ...
    def finish_activity_log(self, run_id: str, status: str) -> None: ...
    def get_activity_log(self, run_id: str) -> Optional[dict[str, Any]]: ...
    def list_activity_logs(self, application_id: Optional[str] = None) -> list[dict[str, Any]]: ...

    # -- users -----------------------------------------------------------
    def get_user(self, email: str) -> Optional[dict[str, Any]]: ...
    def create_user(self, user: dict[str, Any]) -> str: ...


@lru_cache
def get_store() -> Store:
    """Return the configured store singleton."""
    if settings.is_dynamodb_store:
        try:
            from app.services.dynamodb_store import DynamoDBStore

            return DynamoDBStore()
        except (ImportError, Exception) as exc:
            import logging

            logging.warning(
                "DynamoDBStore could not be loaded (%s). Falling back to MemoryStore.", exc
            )

    from app.services.memory_store import MemoryStore

    return MemoryStore()

